### ISSUE TITLE
Project Roadmap

### ISSUE THREAD

**Issue by tgaddair** [predibase/lorax#57]
WIP project roadmap for LoRAX. We'll continue to update this over time.

## Models

- [x] Llama
- [x] Mistral
- [ ] BERT
- [ ] GPT2

## Adapters

- [x] LoRA
- [ ] [Classification Head](https://huggingface.co/blog/Lora-for-sequence-classification-with-Roberta-Llama-Mistral)
- [ ] [Embedding MLP](https://www.linkedin.com/posts/llamaindex_embedding-fine-tuning-is-underrated-and-underexplored-activity-7124106009228320768-Sy3t/?utm_source=share&utm_medium=member_desktop)
- [ ] [Medusa](https://github.com/FasterDecoding/Medusa)
- [ ] [TART](https://hazyresearch.stanford.edu/blog/2023-06-12-icl-vs-finetuning)

## Throughput / Latency

- [x] Paged Attention v2
- [ ] [Lookahead Decoding](https://github.com/hao-ai-lab/LookaheadDecoding)
- [ ] SGMV with variable ranks
- [ ] SGMV with tensor parallelism

## Usability

- [ ] Prebuilt server wheels
- [ ] SkyPilot usage guide
- [ ] Example notebooks

**Comment by RileyCodes** [comment]
is AWQ supported?

**Comment by tgaddair** [comment]
Hey @RileyCodes, not yet, will add that to the roadmap!

**Comment by abhibst** [comment]
does we have tested bitsandbytes Quantization ?

**Comment by tgaddair** [comment]
Hey @abhibst, I've done some basic sanity checks on it, but haven't tested it very thoroughly. Please feel free to report any issues you encounter and I'll take a look!

**Comment by abhibst** [comment]
Sure Thanks for confirming

**Comment by sansavision** [comment]
How would you go about adding this in Stable Diffusion? I am really interested in experimenting with that.

**Comment by tgaddair** [comment]
Hey @sansavision, at a high level it would look a lot like the LoRA pipeline used in Diffusers: https://github.com/huggingface/api-inference-community/blob/main/docker_images/diffusers/app/pipelines/text_to_image.py#L25

A v0 shouldn't be too bad, we would basically just run a single forward pass to generate the image and perform postprocessing (as part of the existing Prefill step) and short-circuit the Decode step.

**Comment by tgaddair** [comment]
Hey @SamGalanakis, great suggestion! The plan at the moment is to start by supporting text classifiers. Once that framework is in place for that, it should be hopefully relatively straightforward to support image classifiers as well. Happy to start a thread on [Discord](https://discord.gg/CBgdrGnZjy) to discuss!

**Comment by flozi00** [comment]
Whisper would be also very cool 😄

**Comment by SamGalanakis** [comment]
@tgaddair Ok clear, joined the discord will look out for it!

**Comment by Hap-Zhang** [comment]
Hi, @tgaddair , could I know how long it will take to support the stable diffusion model?

**Comment by tgaddair** [comment]
Hey @Hap-Zhang, the plan at the moment is to add it after we add support for embedding generation and text classification. Both of those are planned for January 2024, so in the next month.

**Comment by Hap-Zhang** [comment]
@tgaddair Okay, got it. Thank you very much for your efforts. Stay tuned for it.

**Comment by tgaddair** [comment]
Hey @AdithyanI, yes, this should be coming this week or next! See #145 to follow progress.

**Comment by AdithyanI** [comment]
@tgaddair oh wow that would be awesome! Thank you so much for the work here.
If you need someone to test it out; let me know. Happy to test it out.

**Comment by tgaddair** [comment]
@AdithyanI this should be landing some time today :)

#170

**Comment by AdithyanI** [comment]
@tgaddair I asked for outlines repo authors to add support to this : https://github.com/outlines-dev/outlines/discussions/523
Then it would be great to have text guided generation :) 

<img width="600" alt="image" src="https://github.com/predibase/lorax/assets/12037164/74f89f97-2734-469a-abe9-96dac668edca">


I don't know how hard is it to integrate that here. 
Do you folks know if this is something that can be supported by LORAX?

**Comment by tgaddair** [comment]
Thanks for starting the Outlines thread @AdithyanI! Looks like the maintainer created an issue #176. Excited to explore this integration!

**Comment by thincal** [comment]
About the supported models, could you consider the ChatGLM3 ? @tgaddair

**Comment by thincal** [comment]
> * LongLoRA

It seems that LongLoRA proposed `shifted short attention` is compatible with Flash-Attention, and not required during inference (ref: https://huggingface.co/Yukang/Llama-2-13b-longlora-8k#highlights), if that is true, could you share what's the planed support in LoRAX inference side? thanks @tgaddair

**Comment by remiconnesson** [comment]
Do you plan on supporting AQLM to see ve LoRa of Mixtral Instruct with Lorax?

**Comment by tgaddair** [comment]
Hey @thincal, the last thing we need to support LongLoRA, if I remember correctly, is #231 which @geoffreyangus is planning to pick up next week.

@remiconnesson, we have PR #233 from @flozi00 for AQLM. It's pretty close to landing, but just needs a little additional work to finish it up. If no one else picks it up, I can probably take a look in the next week or two.

**Comment by amir-in-a-cynch** [comment]
Are T5 based models on the Roadmap?

**Comment by tgaddair** [comment]
Hey @remiconnesson, will probably be the next thing I take a look at after wrapping up speculative decoding this week.

@amir-in-a-cynch we can definitely add T5 to the roadmap!

**Comment by tomrance** [comment]
Hello, will you integrate / merge / migrate to the latest hugging face [text-generation-inference](https://github.com/huggingface/text-generation-inference) as it is back now with Apache 2.0 license?

**Comment by bdalal** [comment]
Is there an expected release date for v0.11?

**Comment by koleshjr** [comment]
Hey, Any plans to add support for : qwen2_vl ?

**Comment by mrcchef** [comment]
Hi, Any plans for adding bean search support @tgaddair ?

**Comment by thincal** [comment]
@tgaddair hi, is there any new develop plan for this project?

**Comment by ShahNewazKhan** [comment]
Adding myself to the thread in case there are an future updates
